// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEIuW7WnTXm7MNHX_-kU4rA8rSx30k9Og',
    appId: '1:486795717905:web:f8912113ba9222b9dd30b0',
    messagingSenderId: '486795717905',
    projectId: 'meditime-prod',
    authDomain: 'meditime-prod.firebaseapp.com',
    storageBucket: 'meditime-prod.firebasestorage.app',
    measurementId: 'G-JQY9NF2ETM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSy-PLACEHOLDER-KEY-FOR-ANDROID',
    appId: '1:123456789:android:placeholder',
    messagingSenderId: '123456789',
    projectId: 'meditime-prod',
    storageBucket: 'meditime-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSy-PLACEHOLDER-KEY-FOR-IOS',
    appId: '1:123456789:ios:placeholder',
    messagingSenderId: '123456789',
    projectId: 'meditime-prod',
    storageBucket: 'meditime-prod.appspot.com',
    iosBundleId: 'com.example.mediTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSy-PLACEHOLDER-KEY-FOR-MACOS',
    appId: '1:123456789:ios:placeholder',
    messagingSenderId: '123456789',
    projectId: 'meditime-prod',
    storageBucket: 'meditime-prod.appspot.com',
    iosBundleId: 'com.example.mediTime',
  );
}
